url: "https://www.di.ens.fr/willow/research/headdetection/release/HollywoodHeads.zip"
repo_owner: "AbhijithP96"
repo_name: "yolo-head-detection"

training:
  exp: "dvc-pipeline-test"
  run: "yolov8n-2"
  model: "yolov8n.pt"
  batch: 10
  epochs: 5
  patience: 3
  optimizer: 'SGD'
  lr0: 0.0001
  scale: 0.7
  mosaic: 1.0
  cutmix: 0.0