url: "https://www.di.ens.fr/willow/research/headdetection/release/HollywoodHeads.zip"

training:
  exp: "head-detect-trial"
  run: "yolo8n-train-trial"
  model: "yolov8n.pt"
  batch: 10
  epochs: 40
  patience: 5
  optimizer: 'SGD'
  lr0: 0.0001
  scale: 0.7
  mosaic: 1.0
  cutmix: 0.0