url: "https://www.di.ens.fr/willow/research/headdetection/release/HollywoodHeads.zip"

training:
  exp: "model-training-final"
  run: "yolov8n-head-detect"
  model: "yolov8n.pt"
  batch: 10
  epochs: 20
  patience: 3
  optimizer: 'SGD'
  lr0: 0.0001
  scale: 0.7
  mosaic: 1.0
  cutmix: 0.0