url: "https://www.di.ens.fr/willow/research/headdetection/release/HollywoodHeads.zip"
tracking_uri: "https://dagshub.com/AbhijithP96/yolo-head-detection.mlflow"

training:
  exp: "model-training-win"
  run: "yolov8n-head-detection"
  model: "yolov8n.pt"
  batch: 10
  epochs: 20
  patience: 3
  optimizer: 'SGD'
  lr0: 0.0001
  scale: 0.7
  mosaic: 1.0
  cutmix: 0.0